services:
  postgres:
    image: postgres:16
    container_name: swipesound-db
    restart: always
    environment:
      POSTGRES_USER: swipesound_user
      POSTGRES_PASSWORD: swipesound_password
      POSTGRES_DB: swipesound
    ports:
      - '5444:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
